Issue #92 - Added checking environment in pre-flight script

diff --git a/pre-flight b/pre-flight
--- a/pre-flight
+++ b/pre-flight
@@ -4,17 +4,15 @@
 
 GIT_REPOSITORY="https://github.com/CsteerDevops1/wiki-framework"
 GIT_BRANCH="develop"
-EDITORBOT_PATH=""
-SEARCHBOT_PATH=""
-PROJECT_DIR=$1
+PROJECT_DIR=$1 # if blank uses "wiki-framework"
 
-#-------------------- CHECK OUT --------------------
+#-------------------- CHECKING DEPENDENCIES --------------------
 
 git --version &> /dev/null && TEST_G=1 || TEST_G=0
 docker ps &> /dev/null && TEST_D=1 || TEST_D=0
 docker-compose --version &> /dev/null && TEST_DC=1 || TEST_DC=0
 
-#-------------------- UPDATE APT --------------------
+#-------------------- UPDATING APT --------------------
 
 if [ $TEST_G -eq 0 -o $TEST_D -eq 0 -o $TEST_DC -eq 0 ]; then
 	echo -n "Updating apt - "
@@ -22,7 +20,7 @@ if [ $TEST_G -eq 0 -o $TEST_D -eq 0 -o $TEST_DC -eq 0 ]; then
 		&& echo "OK" || echo "Failed"
 fi
 
-#-------------------- INSTALL GIT --------------------
+#-------------------- INSTALLING GIT --------------------
 
 if [ $TEST_G -eq 0 ]; then
 	echo -n "Installing git - "
@@ -30,16 +28,17 @@ if [ $TEST_G -eq 0 ]; then
 		&& echo "OK" || echo "Failed"
 fi
 
-#-------------------- INSTALL DOCKER --------------------
+#-------------------- INSTALLING DOCKER --------------------
 
 if [ $TEST_D -eq 0 ]; then
 	echo -n "Installing docker - "
 	sudo apt install docker.io -y &> /dev/null && \
 		sudo usermod -aG docker $USER \
 			&& echo "OK" || echo "Failed"
+	echo "Please relogin to add current user in docker group"
 fi
 
-#-------------------- INSTALL DOCKER-COMPOSE --------------------
+#-------------------- INSTALLING DOCKER-COMPOSE --------------------
 
 if [ $TEST_DC -eq 0 ]; then
 	echo -n "Installing docker-compose - "
@@ -47,12 +46,18 @@ if [ $TEST_DC -eq 0 ]; then
 		&& echo "OK" || echo "Failed"
 fi
 
-#-------------------- CLONE GIT --------------------
-
+#-------------------- CLONNING GIT --------------------
+GIT_STATUS=0
 if [ "$PROJECT_DIR" = "" ]; then PROJECT_DIR="wiki-framework"; fi
 if ! [ `ls -A $PROJECT_DIR 2> /dev/null | wc -l` -eq 0 ]; then 
-	echo "Directory $PROJECT_DIR already exists and not empty."
-	echo "Please choose another or use deploy script to update project."
+	cd $PROJECT_DIR
+	if [ "$(git remote get-url origin 2> /dev/null)" = "$GIT_REPOSITORY" ]; then
+		GIT_STATUS=1
+	else
+		echo "Directory $PROJECT_DIR already exists and not empty"
+		echo "Please choose another project directory"
+	fi
+	cd ../
 	PROJECT_DIR_STATUS=0
 else
 	PROJECT_DIR_STATUS=1
@@ -60,9 +65,37 @@ fi
 if [ $PROJECT_DIR_STATUS -eq 1 ]; then
 	echo -n "Clonning git into $PROJECT_DIR - "
 	git clone -b $GIT_BRANCH $GIT_REPOSITORY $PROJECT_DIR &> /dev/null \
-	&& echo "OK" || echo "Failed"
+		&& echo "OK" && GIT_STATUS=1 || echo "Failed"
 fi
 
-#-------------------- MESSAGE --------------------
+# Creating empty .env files for docker-compose
+# Using to not break existing condition
+#touch $PROJECT_DIR/telegramBots/userBot/.env
+#touch $PROJECT_DIR/telegramBots/editBot/.env
 
-echo "Please add environment variables to start project"
+#-------------------- CHECKING ENVIRONMENT --------------------
+
+if [ $GIT_STATUS -eq 1 ]; then
+	for env_var in \
+		MONGO_UID \
+		MONGO_GID \
+		REACT_APP_HOSTNAME \
+		TRANSLATOR_API_KEY \
+		TG_USERBOT_TOKEN \
+		TG_EDITORBOT_TOKEN \
+		PROXY_URL \
+		PROXY_LOGIN \
+		PROXY_PASSWORD
+	do
+		if [ "${!env_var}" = "" ]; then 
+			ENV_VARS="$ENV_VARS\n$env_var"
+		fi
+	done
+	
+	if ! [ "$ENV_VARS" = "" ]; then
+		echo -n "Please add environment variables before start project:"
+		echo -e "$ENV_VARS"
+	else
+		echo "You are ready to start project!"
+	fi
+fi
